### ISSUE TITLE
Zelda Port not embeddable

### ISSUE THREAD

**Issue by AT3META** [connorjclark/ZeldaClassic#2]
Hello, 
I've tried to port the Zelda game through my website. It hangs and doesn't initialize. Any thoughts? It is an attempt to embed the Zelda Port to an installation of OSSN 5.6. Many thanks!
![ZeldaPorting](https://user-images.githubusercontent.com/58276731/187305542-ad66f822-e419-420a-bbd6-ce701f0e4365.png)

**Comment by connorjclark** [comment]
Any errors in the browser console?

**Comment by AT3META** [comment]
![image](https://user-images.githubusercontent.com/58276731/193103520-dff24ad6-3c05-40bc-8811-3bf629a21123.png)
Uncaught ReferenceError: SharedArrayBuffer is not defined
    at zelda.js:1:12920

**Comment by connorjclark** [comment]
You need to set two response headers for your page:

```
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Embedder-Policy: require-corp
```

I was surprised to find this would be necessary for the page embedding the iframe, but apparently it is. my website serves these headers because they are necessary to enable certain higher-risk JS apis.

**Comment by AT3META** [comment]
Here is my code for the embedded iframe. Can you suggest where to put this code?
`<iframe
    width="777"
    height="444"
    frameborder="0"
    src="https://hoten.cc/zc/play/"
    allowfullscreen>
</iframe>           
 
<p>
	<button class="btn btn-primary" align="center" onclick="NewTab()"> 
    FULLSCREEN 
    </button> 
    <script> 
        function NewTab() { 
            window.open("https://hoten.cc/zc/play/", 
                    "", "width=100%, height=100%"); 
        } 
    </script>
</p>`

Many thanks!

**Comment by AT3META** [comment]
`<iframe
    width="777"
    height="444"
    frameborder="0"
    src="https://hoten.cc/zc/play/"
    allowfullscreen>
</iframe>           
 
<p>
	<button class="btn btn-primary" align="center" onclick="NewTab()"> 
    FULLSCREEN 
    </button> 
    <script> 
        function NewTab() { 
            window.open("https://hoten.cc/zc/play/", 
                    "", "width=100%, height=100%"); 
        } 
    </script>
</p>`

**Comment by AT3META** [comment]
Here is my code for the page. Can you suggest where to put this recommendation? Many thanks!
 
![image](https://user-images.githubusercontent.com/58276731/193133900-02fbfe39-5c78-47a2-b753-4246c06d38a3.png)

**Comment by connorjclark** [comment]
Sorry, I can't. You need to configure your webserver to add the correct headers.

Good luck!

**Comment by connorjclark** [comment]
FYI, new web feature is landing in Chrome soon to avoid this COEP problem when embedding third-party iframes that you don't need special access to.

https://bugs.chromium.org/p/chromium/issues/detail?id=1226469
https://github.com/camillelamy/explainers/blob/main/anonymous_iframes.md

`<iframe src=example.com credentials=omit>`

I think currently it is behind a chrome flag `AnonymousIframe`.
