### ISSUE TITLE
Certificate of https://hoten.cc/zc/play/ is expired

### ISSUE THREAD

**Issue by tomayac** [connorjclark/ZeldaClassic#3]
![Screenshot 2023-03-23 at 10 40 49](https://user-images.githubusercontent.com/145676/227163452-2bfa4690-fc55-47ac-9887-bea92d802901.png)

Maybe you can fix this, @connorjclark? Thank you!

**Comment by connorjclark** [comment]
Thanks for letting me know,. Forgot to mention I fixed this about a week ago.
